env:
  - PPA=avsm/ocaml312+opam12 DOCS=no
  - PPA=avsm/ocaml312+opam12 LWT=yes DOCS=no
  - PPA=avsm/ocaml40+opam12
  - PPA=avsm/ocaml40+opam12 LWT=yes
  - PPA=avsm/ocaml41+opam12
  - PPA=avsm/ocaml41+opam12 LWT=yes
  - PPA=avsm/ocaml42+opam12
  - PPA=avsm/ocaml42+opam12 LWT=yes COVERALLS=yes

before_script:
  - sudo add-apt-repository -y ppa:$PPA
  - sudo apt-get update
  - sudo apt-get install ocaml-nox opam
  - ocaml -version
  - opam init -y
  - eval `opam config env`

script:
  - "[ -z $LWT ] || opam install -y lwt js_of_ocaml"
  - "[ -z $COVERALLS ] || opam install -y bisect_ppx ocveralls"
  - opam install -y ounit js_of_ocaml lambdasoup
  - make install
  - make dependency-test
  - make test
  - make performance-test
  - "[ -z $LWT ] || make js-test"
  - "[ -n $DOCS ] || make docs"
  - "[ -z $COVERALLS ] || ocveralls --prefix _build bisect*.out --send"
